### PR TITLE
feat : SlideShow working (#51)

### PR DESCRIPTION
**Pull request by kumaryogesh17**
#51

https://github.com/anicmarko9/eu-tours/assets/82561880/e5652b67-cc7a-43de-943c-66ebc38b0519

### CODE REVIEW

**Review by anicmarko9 — COMMENTED** [review]
Does this work on the smaller screens? 320px, 700px, 1000px, 1920px?

Do you have any plans about implementing the animation? What do you think are the best options? I'm more for something like "slide" to the side for 300ms.

**Comment by kumaryogesh17** [comment]
@anicmarko9 ,

Yes It works in small screens.
We can use https://github.com/framer/motion (Framer motion) for animations

**Comment by kumaryogesh17** [comment]
https://github.com/anicmarko9/eu-tours/assets/82561880/50556ca9-2fc7-4eb4-9e66-fa3228f46a43

**Comment by anicmarko9** [comment]
Alright, nice. I will merge this later today when I get free time so I can make sure that deployment doesn't fail. Thank you for your contribution.

P.S.
I have small screen where it shows 4 images instead of 3, that's what I asked about responsiveness. Don't worry, I will check it out later.

**Review by anicmarko9 — APPROVED** [review]
We can use Framer Motion. I didn't use it before, but I'm willing to learn about it some day, probably by the end of this week.

**Pull request merged**
